# Generated by Django 5.2.11 on 2026-03-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('reservation_date', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(max_length=20)),
                ('guest_document', models.CharField(max_length=50)),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('card_brand', models.CharField(max_length=20)),
                ('tokenization_id', models.CharField(max_length=100)),
                ('authorization_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'reservations',
                'managed': False,
            },
        ),
    ]
