# Generated by Django 5.2.11 on 2026-03-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=8)),
                ('payment_type', models.CharField(max_length=7)),
                ('status', models.CharField(max_length=9)),
                ('card_last_four', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
    ]
